---
name: geo_issuable_metric_image_upload_replication
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/589925
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/236108
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/589924
milestone: '19.1'
group: group::geo
type: ops
default_enabled: false
