---
name: geo_blob_download_with_gitlab_http
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/595139
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/230361
rollout_issue_url:
milestone: '18.11'
group: group::geo
type: ops
default_enabled: false
