# @feature_category: vulnerability_management
query organizationMttrOverTime(
  $projectId: [ID!]
  $reportType: [VulnerabilityReportType!]
  $startDate: ISO8601Date!
  $endDate: ISO8601Date!
  $severity: [VulnerabilitySeverity!]
) {
  namespace: organization {
    id
    securityMetrics(projectId: $projectId, reportType: $reportType) {
      __typename
      mttrOverTime(startDate: $startDate, endDate: $endDate, severity: $severity) @client {
        startDate
        endDate
        sumDays
        count
        mttr
        bySeverity {
          severity
          sumDays
          count
          mttr
        }
        byReportType {
          reportType
          sumDays
          count
          mttr
        }
      }
    }
  }
}
