export const mockSubscriptionCreditsUsageData = {
  data: {
    subscriptionUsage: {
      __typename: 'SubscriptionCreditsUsage',
      enabled: true,
      isOutdatedClient: false,
      startDate: '2026-02-01',
      endDate: '2026-02-28',
      creditsUsed: 13800,
      dailyAverage: 616,
      dailyUsage: [
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 320, date: '2026-02-01' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 540, date: '2026-02-02' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 920, date: '2026-02-03' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 610, date: '2026-02-04' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 480, date: '2026-02-05' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 760, date: '2026-02-06' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 680, date: '2026-02-07' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 180, date: '2026-02-08' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 800, date: '2026-02-09' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: null, date: '2026-02-10' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 320, date: '2026-02-11' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 540, date: '2026-02-12' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 0, date: '2026-02-13' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 610, date: '2026-02-14' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 380, date: '2026-02-15' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 760, date: '2026-02-16' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 980, date: '2026-02-17' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 180, date: '2026-02-18' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 680, date: '2026-02-19' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 480, date: '2026-02-20' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 320, date: '2026-02-21' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 540, date: '2026-02-22' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 920, date: '2026-02-23' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 610, date: '2026-02-24' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 480, date: '2026-02-25' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 760, date: '2026-02-26' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 680, date: '2026-02-27' },
        { __typename: 'SubscriptionCreditsDailyUsage', creditsUsed: 900, date: '2026-02-28' },
      ],
      usersUsage: {
        __typename: 'GitlabSubscriptionUsageUsersUsage',
        totalActiveUsers: 215,
        users: {
          __typename: 'SubscriptionCreditsUserConnection',
          pageInfo: {
            __typename: 'PageInfo',
            hasNextPage: true,
            hasPreviousPage: false,
            startCursor: 'usersStartCursor',
            endCursor: 'usersEndCursor',
          },
          nodes: [
            {
              __typename: 'SubscriptionCreditsUser',
              id: 'user_1',
              name: 'Alice Johnson',
              username: 'ajohnson',
              avatarUrl:
                'https://www.gravatar.com/avatar/00000000000000000000000000000001?d=identicon',
              entityType: 'user',
              usage: { __typename: 'SubscriptionCreditsUserUsage', totalCreditsUsed: 1240 },
              blockedStatus: { __typename: 'GitlabSubscriptionUsageBlockedStatus', blocked: true },
            },
            {
              __typename: 'SubscriptionCreditsUser',
              id: 'user_2',
              name: 'Bob Smith',
              username: 'bsmith',
              avatarUrl:
                'https://www.gravatar.com/avatar/00000000000000000000000000000002?d=identicon',
              entityType: 'non_human',
              usage: { __typename: 'SubscriptionCreditsUserUsage', totalCreditsUsed: 890 },
              blockedStatus: { __typename: 'GitlabSubscriptionUsageBlockedStatus', blocked: false },
            },
            {
              __typename: 'SubscriptionCreditsUser',
              id: 'user_3',
              name: 'Carol White',
              username: 'cwhite',
              avatarUrl:
                'https://www.gravatar.com/avatar/00000000000000000000000000000003?d=identicon',
              entityType: 'user',
              usage: { __typename: 'SubscriptionCreditsUserUsage', totalCreditsUsed: 670 },
              blockedStatus: { __typename: 'GitlabSubscriptionUsageBlockedStatus', blocked: false },
            },
            {
              __typename: 'SubscriptionCreditsUser',
              id: 'user_4',
              name: 'Dan Lee',
              username: 'dlee',
              avatarUrl:
                'https://www.gravatar.com/avatar/00000000000000000000000000000004?d=identicon',
              entityType: 'user',
              usage: { __typename: 'SubscriptionCreditsUserUsage', totalCreditsUsed: 510 },
              blockedStatus: { __typename: 'GitlabSubscriptionUsageBlockedStatus', blocked: false },
            },
            {
              __typename: 'SubscriptionCreditsUser',
              id: 'user_5',
              name: 'Eve Chen',
              username: 'echen',
              avatarUrl:
                'https://www.gravatar.com/avatar/00000000000000000000000000000005?d=identicon',
              entityType: 'user',
              usage: { __typename: 'SubscriptionCreditsUserUsage', totalCreditsUsed: 1000 },
              blockedStatus: { __typename: 'GitlabSubscriptionUsageBlockedStatus', blocked: false },
            },
          ],
        },
      },
      products: [
        {
          __typename: 'GitlabSubscriptionUsageProduct',
          id: 'hosted_runners',
          title: 'Hosted Runners',
          creditsUsed: 3200,
          flowTypes: [],
        },
        {
          __typename: 'GitlabSubscriptionUsageProduct',
          id: 'compute_minutes',
          title: 'Compute Minutes',
          creditsUsed: 2800,
          flowTypes: [],
        },
        {
          __typename: 'GitlabSubscriptionUsageProduct',
          id: 'product_analytics',
          title: 'Product Analytics',
          creditsUsed: 1600,
          flowTypes: [],
        },
        {
          __typename: 'GitlabSubscriptionUsageProduct',
          id: 'storage',
          title: 'Storage',
          creditsUsed: 1460,
          flowTypes: [],
        },
        {
          __typename: 'GitlabSubscriptionUsageProduct',
          id: 'code_review_summary',
          title: 'Code Review Summary',
          creditsUsed: 1240,
          flowTypes: [
            {
              __typename: 'GitlabSubscriptionUsageProductFlowType',
              id: 'code_suggestions',
              title: 'Code Suggestions',
            },
          ],
        },
      ],
    },
  },
};
