---
name: advanced_search_projects_score_function
description: Adds function score for advanced projects search
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/524385
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/236533
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/600434
milestone: '19.1'
group: group::global search
type: gitlab_com_derisk
default_enabled: false
