---
name: compliance_framework_templates
description:
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/591059
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/229699
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/596296
milestone: '19.0'
group: group::compliance
type: gitlab_com_derisk
default_enabled: false
