---
name: duo_workflow_audit_events
description: Enable ingestion of AI audit events from Duo Workflow Service
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/591588
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/227311
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/591588
milestone: '19.0'
group: group::compliance
type: gitlab_com_derisk
default_enabled: false
