---
name: duo_workflow_provider_stickiness
description:
feature_issue_url: https://gitlab.com/gitlab-org/modelops/applied-ml/code-suggestions/ai-assist/-/work_items/2174
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/234255
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/599545
milestone: '19.0'
group: group::ai framework
type: gitlab_com_derisk
default_enabled: false
