---
name: security_inventory_pagination
description:
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/591670
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/225375
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/593037
milestone: '19.0'
group: group::security platform management
type: gitlab_com_derisk
default_enabled: false
