---
name: subscription_com_unification
description: Implements the unified registration flow for .com Subscription purchase.
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/593760
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/230747
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/595630
milestone: '19.0'
group: group::acquisition
type: gitlab_com_derisk
default_enabled: false
