---
name: zoekt_use_total_match_counts
description:
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/591911
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/225509
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/591922
milestone: '18.10'
group: group::global search
type: gitlab_com_derisk
default_enabled: false
