---
title: Approve merge request
name: admin_merge_request
description: Allows approval of merge requests.
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/412708
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/128302
feature_category: source_code_management
milestone: '16.4'
group_ability: false
project_ability: true
enabled_for_project_access_levels: [30, 40, 50]
project_permissions:
  - admin_merge_request
  - build_download_code
  - create_merge_request_from
  - create_merge_request_in
  - download_code
  - read_merge_request
