# frozen_string_literal: true

module API
  module Ai
    module DuoWorkflows
      class CodeReview < ::API::Base
        include PaginationParams
        include APIGuard

        allow_access_with_scope :ai_workflows

        feature_category :duo_code_review

        before do
          authenticate!
          set_current_organization
        end

        helpers do
          def verify_duo_agent_platform_code_review_enabled!
            return if ::Ai::DuoCodeReview.dap?(user: current_user, container: project_from_params)

            forbidden!('You are not allowed to use Duo Code Review through Duo Agent Platform')
          end

          def verify_composite_identity!
            return if valid_service_account?

            forbidden!('This endpoint can only be accessed by Duo Workflow Service')
          end

          # Ensure requests come through Duo Workflow Service via composite identity.
          # Composite identity: service account acts on behalf of human user.
          # - current_user: the human user (e.g., root)
          # - service_account_user: the service account (e.g., duo-developer)
          def valid_service_account?
            service_account = Gitlab::Auth::Identity.resolve_composite_identity_actor(current_user)
            return false unless service_account

            workflow_definition = ::Ai::Catalog::FoundationalFlow['code_review/v1']
            resolved_service_account_result = ::Ai::Catalog::ItemConsumers::ResolveServiceAccountService.new(
              container: project_from_params,
              item: workflow_definition.catalog_item
            ).execute

            return false if resolved_service_account_result.error?

            toplevel_group_service_account = resolved_service_account_result.payload.fetch(:service_account)
            toplevel_group_service_account.id == service_account.id
          end

          def project_from_params
            @project_from_params ||= find_project!(params[:project_id])
          end

          def merge_request_from_params
            @merge_request_from_params ||= find_project_merge_request(
              params[:merge_request_iid],
              project: project_from_params
            )
          end
        end

        namespace :ai do
          namespace :duo_workflows do
            namespace :code_review do
              desc 'Add code review comments to a merge request' do
                detail 'Adds review comments generated by Duo Workflows to a merge request.'
                tags ['gitlab_duo_workflows']
                success code: 200
                failure [
                  { code: 400, message: 'Validation failed' },
                  { code: 401, message: 'Unauthorized' },
                  { code: 403, message: 'Forbidden' },
                  { code: 404, message: 'Not found' }
                ]
              end
              params do
                requires :project_id, type: String,
                  desc: 'The ID or path of the project'
                requires :merge_request_iid, type: Integer,
                  desc: 'The IID of the merge request'
                requires :review_output, type: String,
                  desc: 'The review output from LLM'
                optional :workflow_id, type: Integer,
                  desc: 'The ID of the Duo Workflow session'
              end
              route_setting :lifecycle, :experiment
              route_setting :authorization, skip_granular_token_authorization: :ai_workflows_oauth_auth
              post :add_comments do
                verify_duo_agent_platform_code_review_enabled!
                verify_composite_identity!

                review_output_service = ::Ai::DuoWorkflows::CodeReview::ProcessReviewOutputService.new(
                  user: current_user,
                  project: project_from_params,
                  merge_request: merge_request_from_params,
                  review_output: params[:review_output],
                  workflow_id: params[:workflow_id]
                )

                bad_request!(review_output_service.message) unless review_output_service.valid?

                result = review_output_service.execute
                if result.success?
                  present({ message: 'Comments added successfully' }, with: Grape::Presenters::Presenter)
                else
                  bad_request!(result.message)
                end
              end

              desc 'Fetch the Duo Code Review custom instructions for a merge request' do
                detail 'Fetch all Duo Code Review custom instructions for a merge request.'
                tags ['gitlab_duo_workflows']
                success code: 200
                failure [
                  { code: 400, message: 'Validation failed' },
                  { code: 401, message: 'Unauthorized' },
                  { code: 403, message: 'Forbidden' },
                  { code: 404, message: 'Not found' }
                ]
              end
              params do
                requires :project_id, type: String,
                  desc: 'The ID or path of the project'
                requires :merge_request_iid, type: Integer,
                  desc: 'The IID of the merge request'
              end
              route_setting :lifecycle, :experiment
              route_setting :authorization, skip_granular_token_authorization: :ai_workflows_oauth_auth
              get :custom_instructions do
                instructions = ::Gitlab::Duo::CodeReview::CustomInstructionsResolver
                  .new(project_from_params)
                  .execute(merge_request_from_params)

                result = { instructions: instructions }

                present result, with: Grape::Presenters::Presenter
              end
            end
          end
        end
      end
    end
  end
end
