# @feature_category: duo_agent_platform
query getUserWorkflows(
  $type: String
  $first: Int
  $after: String
  $environment: WorkflowEnvironment
) {
  duoWorkflowWorkflows(type: $type, first: $first, after: $after, environment: $environment) {
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      node {
        id
        lastUpdatedAt: updatedAt
        title: goal
        aiCatalogItemVersionId
        agentName @gl_introduced(version: "18.9.0")
        archived
      }
    }
  }
}
