# frozen_string_literal: true

TEMPLATE_MESSAGE = <<~MSG
  此合并请求需要与 gitaly 协调部署。
  我们会在合并之前确认正在运行的 gitaly 生产版本已经实现了这些新的 gRPC 接口。

  这会在金丝雀版本部署时因为引入[非向后兼容改动]而可能产生的事故。

  1. 识别引入新接口的 gitaly 合并请求。
  1. 验证现有环境组件是否含有 `gprd` 部署。

  [非向后兼容改动]: <!-- https://docs.gitlab.cn/jh/development/multi_version_compatibility.html -->
MSG

changed_lines = helper.changed_lines('Gemfile.lock')
if changed_lines.any? { |line| line =~ /^\+\s+gitaly \(/ }
  warn 'Changing gitaly gem can cause a multi-version incompatibility incident'

  markdown(TEMPLATE_MESSAGE)
end
