# frozen_string_literal: true

require 'spec_helper'

RSpec.describe GitlabSchema.types['GeoRegistryClass'], feature_category: :geo_replication do
  let(:registry_classes) do
    %w[
      ABUSE_REPORT_UPLOAD_REGISTRY
      ACHIEVEMENT_UPLOAD_REGISTRY
      AI_VECTORIZABLE_FILE_UPLOAD_REGISTRY
      ALERT_MANAGEMENT_METRIC_IMAGE_UPLOAD_REGISTRY
      APPEARANCE_UPLOAD_REGISTRY
      BULK_IMPORT_EXPORT_UPLOAD_UPLOAD_REGISTRY
      CI_SECURE_FILE_REGISTRY
      CONTAINER_REPOSITORY_REGISTRY
      DEPENDENCY_LIST_EXPORT_PART_UPLOAD_REGISTRY
      DEPENDENCY_LIST_EXPORT_UPLOAD_REGISTRY
      DEPENDENCY_PROXY_BLOB_REGISTRY
      DEPENDENCY_PROXY_MANIFEST_REGISTRY
      DESIGN_MANAGEMENT_ACTION_UPLOAD_REGISTRY
      DESIGN_MANAGEMENT_REPOSITORY_REGISTRY
      GROUP_UPLOAD_REGISTRY
      GROUP_WIKI_REPOSITORY_REGISTRY
      IMPORT_EXPORT_UPLOAD_UPLOAD_REGISTRY
      ISSUABLE_METRIC_IMAGE_UPLOAD_REGISTRY
      JOB_ARTIFACT_REGISTRY
      LFS_OBJECT_REGISTRY
      MERGE_REQUEST_DIFF_REGISTRY
      ORGANIZATION_DETAIL_UPLOAD_REGISTRY
      PACKAGES_DEBIAN_PROJECT_COMPONENT_FILE_REGISTRY
      PACKAGES_HELM_METADATA_CACHE_REGISTRY
      PACKAGES_NUGET_SYMBOL_REGISTRY
      PACKAGE_FILE_REGISTRY
      PAGES_DEPLOYMENT_REGISTRY
      PERSONAL_SNIPPET_UPLOAD_REGISTRY
      PIPELINE_ARTIFACT_REGISTRY
      PROJECT_IMPORT_EXPORT_RELATION_EXPORT_UPLOAD_UPLOAD_REGISTRY
      PROJECT_REPOSITORY_REGISTRY
      PROJECT_TOPIC_UPLOAD_REGISTRY
      PROJECT_UPLOAD_REGISTRY
      PROJECT_WIKI_REPOSITORY_REGISTRY
      SNIPPET_REPOSITORY_REGISTRY
      SUPPLY_CHAIN_ATTESTATION_REGISTRY
      TERRAFORM_STATE_VERSION_REGISTRY
      UPLOAD_REGISTRY
      USER_PERMISSION_EXPORT_UPLOAD_UPLOAD_REGISTRY
      USER_UPLOAD_REGISTRY
      VULNERABILITY_ARCHIVE_EXPORT_UPLOAD_REGISTRY
      VULNERABILITY_EXPORT_PART_UPLOAD_REGISTRY
      VULNERABILITY_EXPORT_UPLOAD_REGISTRY
      VULNERABILITY_REMEDIATION_UPLOAD_REGISTRY
    ]
  end

  it { expect(described_class.graphql_name).to eq('GeoRegistryClass') }

  it 'exposes the correct registry actions' do
    expect(described_class.values.keys).to match_array(registry_classes)
  end
end
