# frozen_string_literal: true

module Security
  module SecretDetection
    module PartnerTokens
      # Auto-generated by ClientGenerator from a reviewed VendorSpec.
      # Vendor docs: https://docs.datadoghq.com/api/latest/authentication/#validate-api-key
      # Regenerate rather than hand-editing; keep the VendorSpec as the source of truth.
      class DatadogClient < BaseClient
        API_ENDPOINT = 'https://api.datadoghq.com/api/v1/validate'
        ACCEPT_HEADER = 'application/json'
        TOKEN_PATTERN = /\A[a-f0-9]{32}\z/

        private

        def valid_format?(token_value)
          return false unless token_value

          token_value.match?(TOKEN_PATTERN)
        end

        def verify_partner_token(token_value)
          response = make_request(
            API_ENDPOINT,
            method: :get,
            headers: { 'DD-API-KEY' => token_value, 'Accept' => ACCEPT_HEADER }
          )
          analyze_response(response)
        end

        def analyze_response(response)
          case response.code.to_i
          when 200
            token_response(:active)
          when 403
            token_response(:inactive)
          when 429
            raise RateLimitError, 'Datadog rate limited: 429'
          when 500, 502, 503, 504
            raise NetworkError, "Datadog service error: #{response.code}"
          else
            # unknown-never-inactive: unmapped codes are never treated as dead tokens.
            token_response(:unknown)
          end
        end
      end
    end
  end
end
