# frozen_string_literal: true

module Security
  module SecretDetection
    module PartnerTokens
      # Auto-generated by ClientGenerator from a reviewed VendorSpec.
      # Vendor docs: https://devcenter.heroku.com/articles/platform-api-reference#account
      # Regenerate rather than hand-editing; keep the VendorSpec as the source of truth.
      class HerokuClient < BaseClient
        API_ENDPOINT = 'https://api.heroku.com/account'
        ACCEPT_HEADER = 'application/vnd.heroku+json; version=3'

        private

        def verify_partner_token(token_value)
          response = make_request(
            API_ENDPOINT,
            method: :get,
            headers: { 'Authorization' => "Bearer #{token_value}", 'Accept' => ACCEPT_HEADER }
          )
          analyze_response(response)
        end

        def analyze_response(response)
          case response.code.to_i
          when 200
            token_response(:active)
          when 401
            token_response(:inactive)
          when 429
            raise RateLimitError, 'Heroku rate limited: 429'
          when 500
            raise NetworkError, 'Heroku service error: 500'
          when 503
            raise NetworkError, 'Heroku service error: 503'
          else
            # unknown-never-inactive: unmapped codes are never treated as dead tokens.
            token_response(:unknown)
          end
        end
      end
    end
  end
end
