# frozen_string_literal: true

module Security
  module SecretDetection
    module PartnerTokens
      # Auto-generated by ClientGenerator from a reviewed VendorSpec.
      # Vendor docs: https://www.twilio.com/docs/sendgrid/api-reference/api-key-permissions/retrieve-a-list-of-scopes-for-which-this-user-has-access#operation-overview-section-indexable
      # Regenerate rather than hand-editing; keep the VendorSpec as the source of truth.
      class SendgridClient < BaseClient
        API_ENDPOINT = 'https://api.sendgrid.com/v3/scopes'
        ACCEPT_HEADER = 'application/json'
        TOKEN_PATTERN = /\ASG\.[a-zA-Z0-9_\-.]{66}\z/

        private

        def valid_format?(token_value)
          return false unless token_value

          token_value.match?(TOKEN_PATTERN)
        end

        def verify_partner_token(token_value)
          response = make_request(
            API_ENDPOINT,
            method: :get,
            headers: { 'Authorization' => "Bearer #{token_value}", 'Accept' => ACCEPT_HEADER }
          )
          analyze_response(response)
        end

        def analyze_response(response)
          case response.code.to_i
          when 200
            token_response(:active)
          when 401
            token_response(:inactive)
          when 429
            raise RateLimitError, 'Sendgrid rate limited: 429'
          when 500, 502, 503
            raise NetworkError, "Sendgrid service error: #{response.code}"
          else
            # unknown-never-inactive: unmapped codes are never treated as dead tokens.
            token_response(:unknown)
          end
        end
      end
    end
  end
end
