---
description: Tracks when user clicks explore plans cta on trial expired modal with monthly credit commitment
internal_events: true
status: active
action: click_explore_plans_end_of_trial_modal
identifiers:
- project
- namespace
- user
product_group: acquisition
product_categories:
- acquisition
milestone: '19.0'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/231742
tiers:
- free
- premium
- ultimate
