---
description: Tracks when a user clicks the start a free trial CTA on the re-trial card on the group billing page
internal_events: true
status: active
action: click_start_trial_on_retrial_card_group_billing
identifiers:
  - namespace
  - user
product_group: acquisition
product_categories:
  - acquisition
milestone: '19.4'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/issues/625037
tiers:
  - free
