---
description: Tracks when user clicks Purchase GitLab Credits cta on active trial
internal_events: true
status: active
action: click_purchase_credits_cta_active_trial
identifiers:
  - project
  - namespace
  - user
product_group: acquisition
product_categories:
  - subscription_management
milestone: '18.10'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/226401
tiers:
  - free
  - premium
  - ultimate
additional_properties:
  property:
    description: The source location of the click event
