---
description: User deleted a scan profile
internal_events: true
status: active
action: delete_scan_profile
identifiers:
- namespace
- user
product_group: security_platform_management
product_categories:
- security_asset_inventories
- security_testing_configuration
milestone: '19.3'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/250064
tiers:
- ultimate
