---
description: Active Merge Request Approval Policies evaluating SPDX license expressions
internal_events: true
action: enforce_approval_policies_with_license_expressions_in_project
identifiers:
- project
- namespace
additional_properties:
  label:
    description: Whether the licenses were defined as allowlist or denylist
product_group: policy_management
product_categories:
- security_policy_management
milestone: '19.3'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/244664
tiers:
- ultimate
