---
description: The instance-wide Secrets Manager trial was started on a self-managed instance
internal_events: true
status: active
action: secrets_manager_instance_trial_started
identifiers:
- user
product_group: secrets_manager_application
product_categories:
- secrets_management
milestone: '19.4'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/254303
tiers:
- premium
- ultimate
