---
description: A Secrets Manager trial was started for a top-level group
internal_events: true
status: active
action: secrets_manager_trial_started
identifiers:
- namespace
- user
product_group: pipeline_security
product_categories:
- secrets_management
milestone: '19.2'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/241981
tiers:
- premium
- ultimate
