---
description: Unenrollment of a self-managed instance from GitLab Secrets Manager
internal_events: true
status: active
action: unenroll_secrets_manager_for_instance
identifiers:
- user
product_group: secrets_manager_application
product_categories:
- secrets_management
milestone: '19.2'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/241294
tiers:
- ultimate
