# @feature_category: workflow_catalog
#import "~/graphql_shared/fragments/page_info.fragment.graphql"

query aiCatalogAvailableProjects(
  $itemId: AiCatalogItemID!
  $search: String!
  $after: String = ""
  $first: Int!
  $searchNamespaces: Boolean = false
  $sort: String
  $membership: Boolean = true
  $minAccessLevel: AccessLevelEnum
) {
  projects(
    search: $search
    after: $after
    first: $first
    membership: $membership
    minAccessLevel: $minAccessLevel
    searchNamespaces: $searchNamespaces
    sort: $sort
  ) {
    nodes {
      id
      name
      nameWithNamespace
      aiCatalogItemConsumerForItem(id: $itemId) @gl_introduced(version: "19.0.0") {
        id
        enabled
      }
    }
    pageInfo {
      ...PageInfo
    }
  }
}
