---
name: mcp_catalog_agent_tools
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/224998
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/584281
milestone: '18.11'
type: development
group: group::ai framework
default_enabled: false
