# frozen_string_literal: true

require 'spec_helper'

# Auto-generated by ClientGenerator. Covers the vendor's declared status
# mapping; the shared example covers the fail-safe behaviour every
# partner token client must satisfy.
RSpec.describe Security::SecretDetection::PartnerTokens::SendgridClient, feature_category: :secret_detection do
  let(:client) { described_class.new }
  let(:valid_token) { "SG.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" }
  let(:response) { instance_double(Net::HTTPResponse) }

  it_behaves_like 'a partner token client',
    http_method: :get,
    malformed_tokens: ['not-a-real-token', '', nil]

  describe '#verify_token' do
    context 'when the vendor reports the token active' do
      before do
        allow(response).to receive_messages(code: '200', body: '{}')
        allow(Integrations::Clients::HTTP).to receive(:get).and_return(response)
      end

      it 'returns active' do
        expect(client.verify_token(valid_token).active?).to be(true)
      end
    end

    context 'when the vendor reports the token inactive' do
      before do
        allow(response).to receive_messages(code: '401', body: '{}')
        allow(Integrations::Clients::HTTP).to receive(:get).and_return(response)
      end

      it 'returns inactive' do
        expect(client.verify_token(valid_token).inactive?).to be(true)
      end
    end

    context 'with a 403 response' do
      before do
        allow(response).to receive_messages(code: '403', body: '{}')
        allow(Integrations::Clients::HTTP).to receive(:get).and_return(response)
      end

      # SendGrid documents 403 as an unverified sender identity or a temporary
      # sending block, not a dead key, so it must never resolve to inactive.
      it 'returns unknown, never inactive' do
        result = client.verify_token(valid_token)

        expect(result.unknown?).to be(true)
        expect(result.inactive?).to be(false)
      end
    end

    context 'with rate limiting and service errors' do
      using RSpec::Parameterized::TableSyntax

      where(:status_code, :error_class) do
        429 | described_class::RateLimitError
        500 | described_class::NetworkError
        502 | described_class::NetworkError
        503 | described_class::NetworkError
      end

      with_them do
        before do
          allow(response).to receive_messages(code: status_code.to_s, body: '')
          allow(Integrations::Clients::HTTP).to receive(:get).and_return(response)
        end

        it 'raises the appropriate error' do
          expect { client.verify_token(valid_token) }.to raise_error(error_class, /#{status_code}/)
        end
      end
    end
  end
end
