---
name: ai_catalog_restricted_to_group_hierarchy_updated
description: In a group, the AI Catalog restricted to group hierarchy setting is changed
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/work_items/594617
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/233902
feature_category: workflow_catalog
milestone: '19.0'
saved_to_database: true
streamed: true
scope: [Group]
