---
name: dependency_firewall_blocked
description: A dependency is blocked by the dependency firewall policy
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/588486
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/223712
milestone: '19.0'
feature_category: dependency_firewall
saved_to_database: true
streamed: true
scope: [Project]
