---
name: duo_session_deleted
description: Duo session is deleted
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/work_items/593027
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/232456
feature_category: duo_agent_platform
milestone: '19.0'
saved_to_database: true
streamed: true
scope: [Group, Project]
