---
name: duo_secret_detection_fp_detection_enabled_updated
description: GitLab Duo Secret Detection False Positive Detection Feature enabled setting on project changed by Security Manager
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/work_items/603477
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/243208
feature_category: vulnerability_management
milestone: '19.2'
saved_to_database: true
streamed: true
scope: [Project]
