---
name: ldap_group_link_created
description: An LDAP Group Link is created
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/8072
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/252957
feature_category: system_access
milestone: '19.4'
saved_to_database: true
streamed: true
scope: [Group]
