---
name: organization_soft_deleted
description: An organization is soft-deleted
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/work_items/594308
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/235915
feature_category: "organization"
milestone: "19.1"
saved_to_database: true
streamed: true
scope: [Instance]
