---
name: pages_domain_verification_succeeded
description: A Pages domain verification succeeded
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/545633
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/249228
feature_category: pages
milestone: '19.4'
saved_to_database: true
streamed: true
scope: [Project]
