---
name: runner_controller_token_revoked
description: A runner controller token is revoked
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/582008
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/223435
feature_category: continuous_integration
milestone: '18.9'
saved_to_database: true
streamed: true
scope: [Instance]
