---
name: security_scan_profile_update
description: A security scan profile is updated
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/work_items/606347
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/248106
feature_category: security_risk_management
milestone: '19.3'
saved_to_database: true
streamed: true
scope: [Group]
