---
name: security_policy_service_account_branch_deletion_bypass
description: Service account deleted a protected branch by using a bypass
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/578753
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/222195
feature_category: security_policy_management
milestone: '18.9'
saved_to_database: true
streamed: true
scope: [Project]