---
name: ticket_reopened_by_project_bot
description: A Service Desk ticket is reopened using a project access token
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/592448
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/226641
feature_category: service_desk
milestone: '18.10'
saved_to_database: true
streamed: true
scope: [Project]
