---
name: user_username_updated
description:
 A user's username is updated.
 Group scope was [introduced](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/240990) for enterprise users in GitLab 19.2.
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/369329
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/106086
milestone: '15.7'
feature_category: user_profile
saved_to_database: true
streamed: true
scope: [User, Group]
