---
name: user_blocked_by_saml_required_group
description: A user is blocked because they are not a member of a required SAML group
introduced_by_issue: https://gitlab.com/gitlab-org/gitlab/-/issues/578102
introduced_by_mr: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/248851
feature_category: system_access
milestone: '19.4'
saved_to_database: true
streamed: true
scope: [User]
