<script>
import { GlCard } from '@gitlab/ui';
import { s__ } from '~/locale';

export default {
  name: 'AiGovernanceDashboardApp',
  components: {
    GlCard,
  },
  computed: {
    summaryMetrics() {
      return [
        { key: 'agents', label: s__('AiGovernance|AI agents') },
        { key: 'sessions', label: s__('AiGovernance|AI sessions') },
        { key: 'posture', label: s__('AiGovernance|Compliance posture') },
      ];
    },
    cards() {
      return [
        {
          key: 'ai-agents',
          title: s__('AiGovernance|AI agents'),
          description: s__(
            'AiGovernance|Internal and external AI agents active in this group and its projects.',
          ),
        },
        {
          key: 'ai-sessions',
          title: s__('AiGovernance|AI sessions'),
          description: s__('AiGovernance|AI agent sessions and their status over time.'),
        },
        {
          key: 'audit-trail',
          title: s__('AiGovernance|Audit trail'),
          description: s__('AiGovernance|Audit events generated by AI agent activity.'),
        },
        {
          key: 'agent-inventory',
          title: s__('AiGovernance|AI agent inventory'),
          description: s__('AiGovernance|Registered AI agents by user, project, and environment.'),
        },
      ];
    },
  },
};
</script>

<template>
  <div class="gl-mt-5">
    <div class="gl-mb-5 gl-grid gl-grid-cols-1 gl-gap-5 sm:gl-grid-cols-3">
      <div
        v-for="metric in summaryMetrics"
        :key="metric.key"
        :data-testid="`summary-metric-${metric.key}`"
        class="gl-border gl-rounded-base gl-border-section gl-bg-section gl-p-5"
      >
        <div class="gl-text-subtle">{{ metric.label }}</div>
        <div class="gl-mt-2 gl-text-size-h1 gl-font-bold" aria-hidden="true">&mdash;</div>
      </div>
    </div>

    <div class="gl-grid gl-grid-cols-1 gl-gap-5 md:gl-grid-cols-2">
      <gl-card v-for="card in cards" :key="card.key" :data-testid="`dashboard-card-${card.key}`">
        <template #header>
          <h2 class="gl-m-0 gl-text-base gl-font-bold">{{ card.title }}</h2>
        </template>
        <p class="gl-m-0 gl-text-subtle">{{ card.description }}</p>
      </gl-card>
    </div>
  </div>
</template>
