# @feature_category: security_policy_management
query groupPolicyTestRuns($fullPath: ID!, $first: Int = 10) {
  namespace: group(fullPath: $fullPath) {
    id
    securityPolicies(type: PIPELINE_EXECUTION_SCHEDULE_POLICY, relationship: DIRECT) {
      nodes {
        id
        name
        testRuns(first: $first) {
          nodes {
            id
            state
            startedAt
            finishedAt
            duration
            errorMessage
            createdAt
            project {
              id
              fullPath
              name
            }
          }
        }
      }
    }
  }
}
