# @feature_category: consumables_cost_management
#import "~/graphql_shared/fragments/page_info.fragment.graphql"

query getUserSubscriptionUsageEvents(
  $namespacePath: ID
  $username: String
  $flowTypes: [String]
  $first: Int
  $last: Int
  $after: String
  $before: String
) {
  subscriptionUsage(namespacePath: $namespacePath) {
    usersUsage {
      users(username: $username) {
        nodes {
          id
          events(
            flowTypes: $flowTypes
            first: $first
            last: $last
            after: $after
            before: $before
          ) {
            nodes {
              timestamp
              eventType
              flowType
              location {
                __typename
                ... on Project {
                  id
                  name
                  webUrl
                }
                ... on Group {
                  id
                  name
                  webUrl
                }
              }
              creditsUsed
              sessionLink @gl_introduced(version: "18.10.0")
            }
            pageInfo {
              ...PageInfo
            }
          }
        }
      }
    }
  }
}
