# @feature_category: compliance_management
query getProjectExposure(
  $groupFullPath: ID!
  $projectFullPath: ID!
  $isProject: Boolean = false
  $limit: Int
  $agentClass: AiGovernanceAgentClass
) {
  group(fullPath: $groupFullPath) @skip(if: $isProject) {
    id
    aiGovernanceMetrics(agentClass: $agentClass) {
      topProjects(limit: $limit) {
        sessionCount
        project {
          id
          name
          fullPath
          nameWithNamespace
          webUrl
        }
      }
    }
  }
  project(fullPath: $projectFullPath) @include(if: $isProject) {
    id
    aiGovernanceMetrics(agentClass: $agentClass) {
      topProjects(limit: $limit) {
        sessionCount
        project {
          id
          name
          fullPath
          nameWithNamespace
          webUrl
        }
      }
    }
  }
}
