# @feature_category: continuous_delivery

#import "./cd_rollout_steps.fragment.graphql"

query cdApplicationDeploymentFlow($applicationId: CdApplicationID!) {
  organization {
    id
    cdApplication(id: $applicationId) {
      id
      name
      activeRollout: rollouts(statuses: [ACTIVE], first: 1) {
        nodes {
          id
          applicationFlowDefinition {
            id
            version
            definition
          }
          ...CdRolloutSteps
        }
      }
      latestFinishedRollout: rollouts(statuses: [SUCCEEDED, FAILED], first: 1) {
        nodes {
          id
          applicationFlowDefinition {
            id
            version
            definition
          }
          ...CdRolloutSteps
        }
      }
      applicationFlowDefinitions(first: 1) {
        nodes {
          id
          version
          definition
        }
      }
    }
  }
}
