# @feature_category: continuous_delivery

#import "~/graphql_shared/fragments/page_info.fragment.graphql"

query cdApplicationServices(
  $id: CdApplicationID!
  $first: Int
  $after: String
  $last: Int
  $before: String
) {
  organization {
    id
    cdApplication(id: $id) {
      id
      services(first: $first, after: $after, last: $last, before: $before) {
        nodes {
          id
          name
          lastDeployedAt
          serviceEnvironmentHealths {
            nodes {
              id
              health
              environment {
                id
                name
                tier
              }
              deployedVersions(first: 1) {
                nodes {
                  id
                  name
                }
              }
            }
          }
        }
        pageInfo {
          ...PageInfo
        }
      }
    }
  }
}
