# @feature_category: continuous_delivery

query cdService($id: CdServiceID!) {
  organization {
    id
    cdService(id: $id) {
      id
      name
      sync @client
      health @client
      lastDeployed @client
      deployedBy @client
      serviceType @client
      environments @client
      artifactSources {
        nodes {
          id
          sourceRef
          versions {
            nodes {
              id
              name
              digest
              reference
              createdAt
            }
          }
        }
      }
    }
  }
}
