query SubgroupsAndProjects(
  $fullPath: ID!
  $subgroupsFirst: Int
  $subgroupsAfter: String
  $projectsFirst: Int
  $projectsAfter: String
  $canReadAttributes: Boolean!
) {
  group(fullPath: $fullPath) {
    id
    descendantGroups(
      archived: false
      includeParentDescendants: false
      first: $subgroupsFirst
      after: $subgroupsAfter
    ) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        __typename
        id
        name
        descendantGroupsCount
        projectsCount
        path
        fullPath
        avatarUrl
        webUrl
        updatedAt
        analyzerStatuses {
          success
          failure
          notConfigured
          analyzerType
          updatedAt
        }
        vulnerabilityNamespaceStatistic {
          critical
          high
          low
          info
          medium
          unknown
          updatedAt
        }
      }
    }
    projects(
      first: $projectsFirst
      after: $projectsAfter
      includeSubgroups: false
      includeArchived: false
    ) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        __typename
        id
        name
        path
        fullPath
        avatarUrl
        webUrl
        updatedAt
        containerScanningForRegistryEnabled
        vulnerabilityStatistic {
          critical
          high
          low
          info
          medium
          unknown
          updatedAt
        }
        analyzerStatuses {
          status
          analyzerType
          lastCall
          buildId
          updatedAt
        }
        securityAttributes @include(if: $canReadAttributes) {
          nodes {
            id
            securityCategory {
              id
              name
            }
            name
            description
            color
          }
        }
      }
    }
  }
}
