# frozen_string_literal: true

module JH
  module Integrations
    module Base
      module Integration
        extend ActiveSupport::Concern

        prepended do
          has_one :dingtalk_tracker_data, autosave: true,
            inverse_of: :integration,
            foreign_key: :integration_id,
            class_name: 'Integrations::DingtalkTrackerData'
        end

        class_methods do
          extend ::Gitlab::Utils::Override

          override :integration_names
          def integration_names
            return super if graphql_rake_env?

            jh_integrations = %w[ones ligaai shimo]
            jh_integrations << 'dingtalk' if ::Gitlab::CurrentSettings.dingtalk_enabled?
            jh_integrations << 'feishu' if ::Gitlab::CurrentSettings.feishu_enabled?
            jh_integrations << 'feishu_bot' if ::Gitlab::CurrentSettings.feishu_bot_enabled?
            jh_integrations << 'wecom' if ::Feature.enabled?(:wecom_integration)

            super + jh_integrations
          end

          private

          # Make the GraphQL doc generated by `gitlab:graphql:compile_docs` consistent with Upstream
          def graphql_rake_env?
            defined?(Rake) && Rake.application.top_level_tasks.first.to_s.start_with?('gitlab:graphql:')
          end
        end
      end
    end
  end
end
