# @feature_category: ai_agents
query getAgentArtifacts(
  $after: String
  $before: String
  $first: Int
  $last: Int
  $name: String
  $not: DuoWorkflowSessionArtifactNegatedFilterInput
  $startTimeAfter: Time
  $startTimeBefore: Time
  $projectPath: String
  $groupFullPath: ID!
) {
  group(fullPath: $groupFullPath) {
    id
    duoWorkflowSessionArtifacts(
      after: $after
      before: $before
      first: $first
      last: $last
      workflowCreatedAfter: $startTimeAfter
      workflowCreatedBefore: $startTimeBefore
      projectPath: $projectPath
      workflowDefinition: $name
      not: $not
    ) {
      count
      nodes {
        id
        workflowDefinition
        webPath
        auditEventsCount
        workflowCreatedAt
        project {
          id
          name
          webPath
          fullPath
        }
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
    }
  }
}
