# @feature_category: ai_agents
query getProjectAgentArtifacts(
  $after: String
  $before: String
  $first: Int
  $last: Int
  $name: String
  $not: DuoWorkflowSessionArtifactNegatedFilterInput
  $startTimeAfter: Time
  $startTimeBefore: Time
  $triggeredByUserId: UserID
  $projectFullPath: ID!
) {
  project(fullPath: $projectFullPath) {
    id
    duoWorkflowSessionArtifacts(
      after: $after
      before: $before
      first: $first
      last: $last
      workflowCreatedAfter: $startTimeAfter
      workflowCreatedBefore: $startTimeBefore
      workflowDefinition: $name
      triggeredByUserId: $triggeredByUserId
      not: $not
    ) {
      count
      nodes {
        id
        workflowDefinition
        webPath
        downloadPath
        auditEventsCount
        workflowCreatedAt
        project {
          id
          name
          webPath
          fullPath
        }
        triggeredBy {
          id
          name
          username
          avatarUrl
          webPath
        }
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
    }
  }
}
