# @feature_category: ai_agents

query getSessionAuditEvents(
  $sessionId: ID!
  $after: String
  $before: String
  $first: Int
  $last: Int
) {
  aiDuoWorkflow(id: $sessionId) @client {
    auditEvents(after: $after, before: $before, first: $first, last: $last) {
      nodes {
        id
        eventType
        createdAt
        author {
          id
          name
          username
          avatarUrl
          webPath
        }
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
    }
  }
}
