# @feature_category: mcp_server
query listDuoSessions(
  $projectPath: ID
  $statusGroup: DuoWorkflowStatusGroup
  $excludeTypes: [String!]
  $first: Int
  $after: String
) {
  duoWorkflowWorkflows(
    projectPath: $projectPath
    statusGroup: $statusGroup
    excludeTypes: $excludeTypes
    first: $first
    after: $after
  ) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      id
      statusName
      goal
      workflowDefinition
      createdAt
      webUrl
    }
  }
}
