---
name: custom_secret_detection_profiles_ui
description: Manage custom secret detection profiles from the group security configuration page.
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/624191
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/252494
rollout_issue_url:
milestone: '19.4'
group: group::security controls
type: wip
default_enabled: false
