---
name: duo_workflow_read_incremental_checkpoints
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/242398
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/604687
milestone: '19.3'
type: wip
group: group::agent execution
default_enabled: false
