---
name: duo_workflow_incremental_checkpoints
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/239247
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/523854
milestone: '19.2'
type: wip
group: group::agent execution
default_enabled: false
