---
name: dw_read_blobs_graphql
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/243813
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/606989
milestone: '19.3'
type: wip
group: group::agent execution
default_enabled: false
