---
name: dw_read_blobs_api
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/247134
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/606987
milestone: '19.3'
type: wip
group: group::agent execution
default_enabled: false
log_state_changes: true
