---
name: project_secrets_cel_pipeline_auth
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/589520
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/223327
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/590664
milestone: '18.10'
group: group::pipeline security
type: wip
default_enabled: false
