# frozen_string_literal: true

module Ai
  module Catalog
    module GoalTemplates
      class Developer
        class MergedMergeRequest
          TEMPLATE = <<~GOAL.strip
            The merge request %{resource_url} has just been merged. It was implemented
            with Duo Developer sessions with the following session IDs: %{session_ids}
            Whenever you mention a session, link it as
            `%{project_url}/-/automate/agent-sessions/<SESSION_ID>`.

            Distill facts from these sessions' traces into repo harness improvements so
            future agent sessions avoid rediscovering the same things.

            ## 1. Get the traces

            For each session ID:

            ```sh
            glab api "ai/duo_workflows/workflows/<SESSION_ID>/trace.jsonl" > "/tmp/trace-<SESSION_ID>.jsonl"
            ```

            ## 2. Extract evidence

            Traces are JSONL event streams: agent reasoning, tool calls, tool results.
            Analyze them with `run_command` (`grep`, `python3`; `jq` may not be
            installed — use `python3 -c 'import json,sys;…'` as a portable
            alternative) instead of `read_file` to keep token use low.

            Collect findings backed by what actually happened in a trace (cite session
            plus events) — no speculation. Route each finding by root cause:

            1. **Missing binary or dependency** in the agent environment → add it to the
               `setup_script:` list in `.gitlab/duo/agent-config.yml`, creating the file
               if absent. File tools reject this path; read and edit it with `run_command`.
            2. **Misconfigured repo dev setup** (for example a broken hook or script) →
               fix that configuration directly; do not document workarounds instead.
            3. **Convention the agent had to discover by trial and error** (lint, test,
               build commands), or the repo's agent instructions misled it → update those
               instructions.

            For case 3, first determine the repo's convention from the root of the repo,
            then edit accordingly:

            - only `AGENTS.md` → edit it
            - only `CLAUDE.md` → edit it
            - both → if one is a symlink to the other, edit the real file; if independent,
              apply the same change to both
            - neither → create `AGENTS.md`

            These files are loaded into every session of many different agents, so:

            - Add only guidance that holds for common agents (never one agent's tool quirk)
              and for the whole class of mistake (for example how to check out a branch
              whether or not it exists on the remote), not a single incident.
            - Recommend the proper way; add a fallback only where the proper way is
              impractical for an autonomous agent.
            - Keep additions as short as clarity allows — every line costs tokens in every
              future session.

            Drop findings that occurred once with no sign they are systemic, and
            findings owned by files outside this repo (for example a skill hosted
            elsewhere) — mention those in the merge request description as observations
            instead of fixing them here.

            ## 3. Deliver

            If findings remain, apply them and open one merge request:

            - Keep the diff to the routed fixes above; unrelated code fixes and
              refactors are out of scope.
            - Branch off the default branch with a name matching
              `duo/distill/<short-description>`.
            - Commit following the repo's commit conventions (Conventional
              Commits if none are documented).
            - Write the title and description following the project's conventions, using
              a template from `.gitlab/merge_request_templates/` when one exists. For
              each change, state the root cause and why the change is needed with its
              session evidence, concisely enough that a reviewer can merge with
              confidence.
            - Do not create the merge request as a draft.
            - Assign the merge request to `%{author_username}` using `--assignee %{author_username}`.
            - Request review from `%{merged_by_username}` using `--reviewer %{merged_by_username}`.
            - End the description with a feedback section:
              ```
              ## Feedback
              This MR was generated by Duo Developer memory distillation.
              Report issues or share feedback: https://gitlab.com/gitlab-org/gitlab/-/work_items/613978
              ```

            ## 4. Report back

            Post a comment on the merged merge request %{resource_url} summarizing what
            you did: which sessions you analyzed, the key findings, and a link to the
            merge request you opened (or why no changes were needed).

            End the comment with:
            `Feedback or issues? https://gitlab.com/gitlab-org/gitlab/-/work_items/613978`
          GOAL

          def self.template
            TEMPLATE
          end

          def self.vars(resource:, params: {}, **_)
            {
              resource_url: Gitlab::UrlBuilder.build(resource),
              project_url: Gitlab::UrlBuilder.build(resource.project),
              session_ids: Array(params[:session_ids]).join(', '),
              author_username: resource.author&.username,
              merged_by_username: (resource.metrics&.merged_by || resource.author)&.username
            }
          end
        end
      end
    end
  end
end
