---
name: secrets_manager_api_access
description: Enable the non-CI/CD Secrets Manager access token endpoint
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/594090
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/240364
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/594090
milestone: '19.2'
group: group::secrets manager application
type: beta
default_enabled: false
