---
name: secrets_manager_instance_enrollment
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/598522
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/235078
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/599755
milestone: '19.0'
group: group::pipeline security
type: beta
default_enabled: true
