---
name: security_scan_profiles_dependency_scanning
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/593009
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/227565
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/593778
milestone: '18.11'
group: group::security platform management
type: beta
default_enabled: false
