---
name: semantic_search_user_model_selection
description:
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/582638
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/230649
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/597029
milestone: '19.0'
group: group::ai coding
type: beta
default_enabled: false
