---
name: vue3_migrate_ai_governance
description: Enables Vue 3 in compatibility mode for the AI Governance Dashboard page
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/607945
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/248557
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/607945
milestone: '19.3'
group: group::compliance
type: beta
default_enabled: false
