---
name: vue3_migrate_secret_detection_exclusions
description: Enables Vue 3 in compatibility mode for the Secret Detection exclusions page
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/607891
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/248359
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/607891
milestone: '19.3'
group: group::secret detection
type: beta
default_enabled: false
