---
name: vue3_migrate_iteration_cadences
description: Enables Vue 3 in compatibility mode for the iteration cadences pages
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/608108
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/249811
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/612741
milestone: '19.4'
group: group::work items
type: beta
default_enabled: false
