---
name: workplan
description: Enables the workplan widget on a work item
feature_issue_url: https://gitlab.com/groups/gitlab-org/-/work_items/21511
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/603128
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/231689
milestone: '19.0'
group: group::planner intelligence
type: beta
default_enabled: false
