---
name: lines_of_code
introduced_by_url: https://jihulab.com/gitlab-cn/gitlab/-/merge_requests/412
rollout_issue_url: https://jihulab.com/gitlab-cn/gitlab/-/issues/795
milestone: '15.0'
type: development
group: group::optimize
default_enabled: false