---
name: tencent_captcha
introduced_by_url: https://jihulab.com/gitlab-cn/gitlab/-/merge_requests/323
rollout_issue_url: https://jihulab.com/gitlab-cn/gitlab/-/issues/488
milestone: '14.9'
type: development
group: group::access
default_enabled: false
