---
key_path: settings.secrets_manager_instance_enrolled
description: Whether GitLab Secrets Manager is enabled at the self-managed instance level
product_group: pipeline_security
product_categories:
- secrets_management
value_type: boolean
status: active
time_frame: none
data_source: system
data_category: optional
instrumentation_class: GitlabSettingsMetric
options:
  setting_method: secrets_manager_instance_enrolled?
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/241294
performance_indicator_type: []
tiers:
- ultimate
milestone: '19.2'
