export const mockBillingPageAttributes = {
  seatsInUse: 1,
  trialActive: false,
  trialExpired: false,
  manageSeatsPath: '__manage_seats_path__',
  startTrialPath: '__start_trial_path__',
  upgradeToPremiumUrl: '__upgrade_to_premium_url__',
  upgradeToUltimateUrl: '__upgrade_to_ultimate_url__',
  upgradeToPremiumTrackingUrl: '__upgrade_to_premium_tracking_url__',
  upgradeToUltimateTrackingUrl: '__upgrade_to_ultimate_tracking_url__',
  totalSeats: 5,
  trialEndsOn: null,
  canAccessDuoChat: true,
  exploreLinks: {
    duoChat: '__duo_chat_path__',
    mergeTrains: '__merge_trains_path__',
    epics: '__epics_path__',
    escalationPolicies: '__escalation_policies_path__',
    repositoryPullMirroring: '__repository_pull_mirroring_path__',
    mergeRequestApprovals: '__merge_request_approvals_path__',
  },
};
