# @feature_category: artifact_registry
#import "~/graphql_shared/fragments/page_info.fragment.graphql"

query getArtifactRegistryRepositoryPackages(
  $organizationId: OrganizationsOrganizationID!
  $name: String!
  $first: Int
  $last: Int
  $before: String
  $after: String
) {
  organization(id: $organizationId) {
    id
    artifactRegistryRepository(name: $name) {
      name
      format
      packages(first: $first, last: $last, before: $before, after: $after) @client {
        nodes {
          ... on ArtifactRegistryMavenPackage {
            id
            groupId
            artifactId
          }
          ... on ArtifactRegistryNpmPackage {
            id
            name
            scope
            versionsCount
          }
        }
        pageInfo {
          ...PageInfo
        }
      }
    }
  }
}
