#import "./work_item_agent_plan.fragment.graphql"

# @feature_category: team_planning
subscription workItemAgentPlanUpdated(
  $id: WorkItemID!
  $useWorkItemFeatures: Boolean = false
  $includeReadinessScore: Boolean = false
) {
  workItemUpdated(workItemId: $id) {
    id
    iid
    widgets @skip(if: $useWorkItemFeatures) {
      ... on WorkItemWidgetAgentPlan {
        ...WorkItemAgentPlanFragment
      }
    }
    features @include(if: $useWorkItemFeatures) {
      agentPlan {
        ...WorkItemAgentPlanFragment
      }
    }
  }
}
