# @feature_category: secrets_management
mutation createGroupSecret(
  $fullPath: ID!
  $name: String!
  $description: String!
  $secret: String!
  $environment: String!
  $protected: Boolean!
  $rotationIntervalDays: Int
) {
  secretCreate: groupSecretCreate(
    input: {
      groupPath: $fullPath
      name: $name
      description: $description
      secret: $secret
      environment: $environment
      protected: $protected
      rotationIntervalDays: $rotationIntervalDays
    }
  ) {
    errors
    groupSecret {
      description
      name
    }
  }
}
