# @feature_category: secrets_management
mutation updateGroupSecret(
  $fullPath: ID!
  $name: String!
  $description: String!
  $secret: String
  $protected: Boolean!
  $environment: String!
  $metadataVersion: Int!
  $rotationIntervalDays: Int
) {
  secretUpdate: groupSecretUpdate(
    input: {
      groupPath: $fullPath
      name: $name
      description: $description
      secret: $secret
      protected: $protected
      environment: $environment
      metadataCas: $metadataVersion
      rotationIntervalDays: $rotationIntervalDays
    }
  ) {
    errors
    groupSecret {
      description
      name
    }
  }
}
