---
key_path: counts.gitlab_secrets_manager_enrolled_namespaces
description: Count of top-level groups enrolled in GitLab Secrets Manager
product_group: pipeline_security
product_categories:
- secrets_management
value_type: number
status: active
time_frame: all
data_source: database
data_category: optional
instrumentation_class: SecretsManagement::CountEnrolledNamespacesMetric
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/241294
performance_indicator_type: []
tiers:
- ultimate
milestone: '19.2'
