---
key_path: counts.count_total_secrets_manager_access_denied
description: Total count of times Secrets Manager access was denied because of the
  namespace's entitlement state
product_group: secrets_manager_application
product_categories:
- secrets_management
performance_indicator_type: []
value_type: number
status: active
milestone: '19.3'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/245606
time_frame:
- 28d
- 7d
- all
data_source: internal_events
data_category: optional
tiers:
- premium
- ultimate
events:
- name: secrets_manager_access_denied
