---
key_path: counts.count_total_trigger_resolve_dependency_bump_workflow
description: Count of resolve dependency bump breaking changes resolution workflows triggered.
product_group: composition_analysis
product_categories:
  - dependency_management
performance_indicator_type: []
value_type: number
status: active
milestone: '19.2'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/244625
time_frame:
  - 28d
  - 7d
  - all
data_source: internal_events
data_category: optional
tiers:
  - ultimate
events:
  - name: trigger_resolve_dependency_bump_workflow
