---
key_path: counts.count_total_secrets_manager_add_on_enabled
description: Total count of times the Secrets Manager paid add-on was enabled without a trial, for a top-level group on GitLab.com or for a GitLab Self-Managed instance
product_group: secrets_manager_application
product_categories:
- secrets_management
performance_indicator_type: []
value_type: number
status: active
milestone: '19.4'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/254563
time_frame:
- 28d
- 7d
- all
data_source: internal_events
data_category: optional
tiers:
- premium
- ultimate
events:
- name: secrets_manager_add_on_enabled
