---
key_path: counts.count_root_namespace_scan_profiles
description: Count of root namespaces with scan profiles
product_group: security_platform_management
product_categories:
- security_testing_configuration
performance_indicator_type: []
value_type: number
status: active
milestone: '18.10'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/220222
time_frame:
- all
data_source: database
data_category: optional
instrumentation_class: CountRootNamespaceScanProfiles
tiers:
- ultimate
